### ISSUE TITLE
Utils: заменить is_file на file_adapter

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/pynames#6]
1. название функции не отражает суть её проверки;
2. функциоя используется только там, где нужно получить открытый файл и только для этого

Логичным будет вынести всё выражение 

```
templates_source if is_file(templates_source) else open(templates_source)
```

в отдельный context processor, который будет гарантированно возвращать нужный нам объект.

**Comment by imposeren** [comment]
Готово. Возможно стоит переименовать is_file как-то иначе. is_opened_file или is_iterable_context_manager. или is_file_like
