### ISSUE TITLE
Нужен ли AUTOLOAD в табличном генераторе

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/pynames#7]
Данный параметр решает проблему подгрузки фикстур «на лету», но так как Python язык динамический, мы вполне можем налету создавать не инстансы классов, а сами классы, что позволило бы избавиться от данного параметра.

**Comment by imposeren** [comment]
А как предлагается это "вызывать"? Сейчас я делаю так:
1. есть класс с переопреленным методом load_tables: https://bitbucket.org/imposeren/tabletop-planning/src/c3bc0eb74de0e2f9d8cb1c1af370cd4f0b9859b8/tabletop_tools/utils.py?at=master#cl-83
2. данный класс используется в форме: https://bitbucket.org/imposeren/tabletop-planning/src/c3bc0eb74de0e2f9d8cb1c1af370cd4f0b9859b8/tabletop_tools/forms.py?at=master#cl-78

Сама идея генерировать класс на лету неплоха, но вопрос в том как будет выглядеть вызов для этой генерации.

**Comment by imposeren** [comment]
еще как вариант: можно сделать autoload аргументом метода ``__init__``, а не атрибутом класса

**Comment by Tiendil** [comment]
На мой взгляд второй вариант семантически точнее. В данный момент, у нас один генератор — один класс. В этом плане autoload нарушает этот подход.

Если смотреть конкретный случай использования на сайте с Django, то подгружая фикстуры мы как раз имеем целью создать **новый** генератор, соответственно логичным было бы создать новый класс.

Явное лучше неявного :-)

**Comment by imposeren** [comment]
Мне кажется, что в некоторых случаях один и тот же генератор может использоваться с разными tables (при этом с одинаковыми темплейтами и настройками). Так-что грузить всё сразу потенциально вариант так себе. Может стоит сделать self.tables ленивым? И вообще я предлагаю для ``FromTablesGenerator`` сделать методы ``load_settings``, ``load_templates``, ``load_tables``, что бы было меньше отличий между ``FromTablesGenerator`` и ``FromCSVTablesGenerator``

**Comment by Tiendil** [comment]
> Мне кажется, что в некоторых случаях один и тот же генератор может использоваться с разными tables 

Это потенциальный альтернативный подход к организации библиотеки. Изначально можно было бы создавать генераторы не делая отдельные классы, а инстанцируя нужный базовый класс с передачей фикстур в консктруктор. Я не вижу принципиального преимущества у одного из подходов, но для реализации был выбран 1-ый, менять на второй не вижу смысла.

Соответственно, лучше всё-таки убрать autoload.

`load_settings``, ``load_templates``, ``load_tables`` вносить в базовый класс не вижу смысла, т.к. они специфичны для CSV генератора, я бы их в нём даже приватными сделал.

**Comment by imposeren** [comment]
Собственно готово.
