### ISSUE TITLE
Реорганизация структуры генераторов

### ISSUE THREAD

**Issue by Tiendil** [Tiendil/pynames#8]
1. отделить их от основного кода
2. упростить и автоматизировать их структуризацию
3. обеспечить наиболее лёгкий процесс добавления новых генераторов

**Comment by Tiendil** [comment]
Посмотрел одним глазом flask extensions, на мой взгляд, делать генераторы отдельными пакетами точно не стоит — сама библиотека достаточно маленькая и разбивать её на много разных , это усложнять жизнь и разработчикам и пользователям без какого-то существенного профита.

Может быть достаточно вынести их в отдельный подмодулю с плоской структурой, вроде:

```
/pynames
|---/genarators
|---|---elves
|---|---goblins_1
|---|---goblins_2
|---|---…
```

**Comment by imposeren** [comment]
Возможно стоит сделать компромисный вариант:

1. механизм автоматической подгрузки генераторов из разных модулей
2. стандартные генераторы оставить в основном репозитории, но использовать этот механизм. Т.е. что бы при импорте из pynames.generators могли импортироваться сторонние модули если они правильно подготовлены

**Comment by Tiendil** [comment]
Не вижу смысла в регистрации сторонних модулей. Pynames — не фреймворк, а библиотека — тут нет никаких внутренних алгоритмов, которые должны знать о всех генераторах.

Пользователь же и так будет знать все исспользуемые генераторы — так или иначе ему всё равно придётся создать и поддерживать их актуальный список.

get_all_generators полезна в контексте библиотеки, чтобы получить все генераторы, объявленные в библиотеке, поэтому расширять её незачем.

**Comment by imposeren** [comment]
ну тогда вопрос остаётся только в структуре. В текущий момент я пользуюсь тем, что генераторы побиты на подмодули:
http://playhard.kiev.ua/tools/name_generator/
https://bitbucket.org/imposeren/tabletop-planning/src/c3bc0eb74de0e2f9d8cb1c1af370cd4f0b9859b8/tabletop_tools/templates/tabletop_tools/name_generator.html?at=master#cl-23
https://bitbucket.org/imposeren/tabletop-planning/src/c3bc0eb74de0e2f9d8cb1c1af370cd4f0b9859b8/tabletop_tools/utils.py?at=master#cl-76

Так-что мне было бы удобнее если бы либо структура осталась, либо что бы у генератора были какие-то метаданные. Хотя и с плоской структурой можно будет выкрутиться — просто кроме ручного задания verbose_names придётся вручную задавать и категорию.


В случае создания сторонних модулей с генераторами: будут ли приниматься пул-реквесты на добавление ссылок на них в README? Просто pynames вполне можно использовать и как генератор НЕ имён:   
https://dl.dropboxusercontent.com/u/1430394/not_names_generator.png
Так-что добавлять всё подряд не вариант. Даже те генераторы, что я добавлял ранее для Iron Kingdoms уже немного выходят из контекста либы: генерируют полные имена (например "Имя-Мама-Папа-Кличка" для гобберов, и "Имя Фамилия" для всех остальных)

**Comment by Tiendil** [comment]
Можно сделать систему тегов, как минимум три группы напрашиваются: раса (эльфсы, дварфсы), вселенная (ваха, dnd, реальность) и «тип» генератора (если разрашать не только имена).

По поводу не имён, как минимум, вполне допустимо держать в библиотеке генераторы названий мест, артефактов, заклинаний. Соответственно, в этом плане система тегов была бы уместна.

У меня как раз есть библиотека для их реализации: https://github.com/Tiendil/rels — в Сказке очень хорошо прижилась.

Соответственно, каждому генератору можно приписать несколько дополнительных свойств: название, комментарий, список тегов.

**Comment by imposeren** [comment]
а почему бы просто не сделать метадату в виде словарей, или в виде namedtuple? вряд ли в метаданных понадобится что-то кроме "прочитать" значение метаданных

```python
MetaData = namedtuple('Metadata', ['types', 'subtypes', 'methods', 'universes', 'details'])
NameMetaData = namedtuple('NameMetaData', ['races', 'ethnic_groups', 'genders'])

class ThurianMorridaneFullnameGenerator(FromCSVTablesGenerator):
    metadata = MetaData(
        types=['name'],
        subtypes=['fullname'],
        methods=['choices+concat'],
        universes=['IronKingdoms'],
        details=NameMetaData(['human'], ['Thurian', 'Morridane'], ['M', 'F'])
    )
```

Ну разве, что стоит выбрать ограничить тип метаданных (как в моем примере -- списки, либо просто строки)

**Comment by Tiendil** [comment]
Можно и так, только вместо строк всё-таки какие-то фиксированные константы надо сделать, иначе будут проблемы с регистом символов или даже написанием, например, «Iron Kingdoms» можно очень по-разному написать.

Либо ввести какой-то формат этих строк + тесты на его соблюдение (с проверкой по словарю «зарезервированных» слов.

Я бы таки сделал перечисления, хотя бы так, как они сейчас реализованы в relations.py . Получили бы что-то вроде этого:

```python
from pynames import relations

class ThurianMorridaneFullnameGenerator(FromCSVTablesGenerator):
    metadata = MetaData(
        types=[relations.TYPE.NAME],
        subtypes=[relations.SUBTYPE.FULLNAME],
        methods=[relations.MATHOD.CHOICES_CONCAT],
        universes=[relations.UNIVERSE.IRON_KINGDOMS],
        details=NameMetaData(races=[relations.RACE.HUMAN],
                             ethnic_groups=[relations.ETHNIC_GROUP.THURIAN, relations.ETHNIC_GROUPS.MORRIDANE],
                             genders=[relations.GENDER.MALE, relations.GENDER.FEMALE]))
```

**Comment by Tiendil** [comment]
Пока сделал следующее:

- переместил все генераторы в дочерний модуль pynames.generators
- все фикстуры поместил в одну директорию
- генераторы Iron Kingdoms оставил в их модуле (но перенёс его в pynames.generators)
- подрпавил get_all_generators

В необходимости какой-то мета-информации сомневаюсь, так как не ясно даже на каком языке её писать. Думаю, это нужно дать на откуп пользователям библиотеки — каждый может взять нужные генераторы и у себя прописать им нужную информацию.
